# Generated by Django 5.0.2 on 2024-03-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Abreviatura'),
        ),
    ]
